# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HqZtVQ49COBsK5dmUNBk01tryLCB_ss
"""

# File: src/__init__.py
# Menandai direktori 'src' sebagai sebuah Python package.