# -*- coding: utf-8 -*-
"""Predict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HqZtVQ49COBsK5dmUNBk01tryLCB_ss
"""

# File: src/predict.py
import joblib
import os
import pandas as pd

# Path ke file model dan vectorizer yang sudah disimpan
MODEL_PATH = os.path.join('..', 'models', 'svm_model.pkl')
VECTORIZER_PATH = os.path.join('..', 'models', 'tfidf_vectorizer.pkl')

# Memuat model dan vectorizer yang sudah dilatih
try:
    model = joblib.load(MODEL_PATH)
    vectorizer = joblib.load(VECTORIZER_PATH)
    print("Model dan TfidfVectorizer berhasil dimuat.")
except FileNotFoundError as e:
    print(f"Error: File model atau vectorizer tidak ditemukan. Pastikan file berada di direktori 'models'.")
    print(f"Detail error: {e}")
    exit()

# Mapping label untuk output yang mudah dibaca
LABEL_MAPPING = {
    0: "Berapa jarak jangkauan signal wifi 2",
    1: "Information",
    2: "Problem",
    3: "Request"
}

def predict_label(text_list):
    """
    Membuat prediksi label untuk daftar teks yang diberikan.

    Args:
        text_list (list): Daftar teks (string) yang akan diprediksi.

    Returns:
        list: Daftar prediksi label dalam bentuk string.
    """
    if not isinstance(text_list, list):
        text_list = [text_list]

    # Preprocess teks: ubah ke huruf kecil
    preprocessed_text = [text.lower() for text in text_list]

    # Ubah teks menjadi representasi TF-IDF
    text_features = vectorizer.transform(preprocessed_text)

    # Lakukan prediksi
    predictions = model.predict(text_features)

    # Ubah prediksi numerik menjadi label string
    predicted_labels = [LABEL_MAPPING[pred] for pred in predictions]

    return predicted_labels

if __name__ == '__main__':
    # Contoh penggunaan skrip
    new_texts = [
        "internet saya putus, tidak bisa digunakan",
        "ada promo paket baru?",
        "saya ingin pasang wifi di rumah"
    ]

    predictions = predict_label(new_texts)

    # Cetak hasil prediksi
    for text, label in zip(new_texts, predictions):
        print(f"Teks: '{text}' -> Prediksi Label: {label}")